mirror_to_github:
  stage: deploy
  image: alpine:latest
  variables:
    GIT_STRATEGY: clone
  only:
    - main
  before_script:
    - apk update && apk add git openssh-client
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git config --global user.email "${GITLAB_USER_EMAIL}"
  script:
    # Set up GitHub remote
    - git remote add github https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/${GITHUB_USERNAME}/${GITHUB_REPO}.git
    
    # Create actual local branches for each remote branch
    - for branch in $(git branch -r | grep -v '\->'); do
    -   branch_name=$(echo $branch | sed 's/origin\///')
    -   git checkout -b $branch_name $branch
    - done
    
    # Push all branches to GitHub
    - git push github --all
    - git push github --tags
    
    # Verify push
    - echo "Successfully pushed to GitHub"