# System
sys:
  info_level: 3 # 0: no info, 1: INFO tags, 2: DEBUG tags, 3: INFO+DEBUG tags

# Logging
logging:
  level: DEBUG
  format: "[%(asctime)s] - %(name)s -%(levelname)s: %(message)s"

# Vector Store
vector_store:
  dimension: 384
  index_type: "IDMap,Flat"
  metric_type: 1 # faiss.METRIC_L2

# Cache
cache:
  CACHE_DIR: "./persistent_cache"

# Experiment
experiment:
  name: "Quora small batch size"

  # Dataset configuration
  dataset_name: "quora"
  load_from_file: false
  partial_questions: true
  range_min: 0
  range_max: 1000

  # Cache configuration
  use_cache: true
  max_cache_size: 2000
  cache_strategy: "dynamic_eviction" # "memory" or "dynamic_eviction"

  # LSH configuration
  use_LSH: true
  bucket_density_factor: 0.7
  num_hyperplanes: 8
  window_size: 1000
  sensitivity: 2.0
  decay_rate: 5.0
